language:
    - cpp

dist: xenial

install:
    - ls -alF
    - sudo apt-get install gcc-aarch64-linux-gnu
    - sudo apt-get install g++-aarch64-linux-gnu
    - aarch64-linux-gnu-gcc -v
    - aarch64-linux-gnu-g++ -v
    - sudo apt-get install cppcheck

script: 
    - make clean	
    - make
    - ./ascend
    - cppcheck ./*.cpp --enable=all